azs:
- name: z1
- name: z2
- name: z3

compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: default
  workers: 1

disk_types:
- name: default
  disk_size: 3000

networks:
- name: default
  subnets:
  - azs: [z1, z2, z3]
    cloud_properties:
      name: vbox-net
    gateway: 10.10.0.1
    range: 10.10.0.0/16
    static: [10.10.0.10]
    dns: [8.8.8.8]

vm_types:
- name: default
  cloud_properties:
    cpu: 1
    ram: 128
    disk: 3240

